### ISSUE TITLE
About train.py

### ISSUE THREAD

**Issue by XinYuanZhan** [bluedream1121/REKD#1]
Hello, I have configured the experimental environment according to the configuration you posted. But I have the following error
![image](https://user-images.githubusercontent.com/91943342/166098806-0ff6c86d-7844-4ea5-bf7c-767e433190be.png) 
the error shows that there is an error in reading the image path, but I have completed the first generation of training, how can I solve this problem?

**Comment by bluedream1121** [comment]
Did you download the training data for generating synthetic image pairs? e.g., ImageNet 2012 for synthetic dataset generation (6.4G).

**Comment by XinYuanZhan** [comment]
Sorry I got it wrong, I've fixed the problem.
