### ISSUE TITLE
How to reproduce the results on HPatches?(especially for repeatability)

### ISSUE THREAD

**Issue by QYQYQYQYQYQ** [bluedream1121/REKD#10]
Enjoy reading your paper!
But how to reproduce the results?  I run source codes for several times and generate several synthetic datasets, but It's quite different from the results in your paper.(especially for repeatability)
Many thanks.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/30305345/231064341-f1c2049d-2b77-4131-860d-8a6815d8ec81.png">

**Comment by Boluo-XD** [comment]
Hello! I encountered the same situation as you. Have you solved your problem?
