### ISSUE TITLE
Match for homograph

### ISSUE THREAD

**Issue by Kukulin13013** [bluedream1121/REKD#4]
Maybe I missed some code, I don't see the match part. 
I personally used FLANN of opencv to match the two v_boat pic in the demo,  the result is as follow.
I would appreciate it if can guide me to the match part in the project.
![viz2](https://user-images.githubusercontent.com/83392405/174051387-30762630-567e-4988-af4a-e5246f413b3d.jpg)

**Comment by bluedream1121** [comment]
Did you extract the patch descriptor of each keypoint correctly? We use HardNet descriptor for image matching.
