### ISSUE TITLE
eval image pyramid resize axis not aligned?

### ISSUE THREAD

**Issue by Wangweiyao** [bluedream1121/REKD#6]
Hi, I find in the eval script, the image is resized not in the right shape because the axis is not aligned with skimage convention. Could be from a version control problem I guess.

https://github.com/bluedream1121/REKD/blob/main/evaluation/extract_hpatches.py#L92

**Comment by bluedream1121** [comment]
You mean the size of pyramid images is not aligned? The output resolution of image pyramid is compensated by multiplying scale factor after obtaining keypoints. 

The pyramid_gaussian function of scikit-image is an anti-aliased version of image upsamplimg/downsampling.
