### ISSUE TITLE
Implementation of GIFT descriptor

### ISSUE THREAD

**Issue by ph-code-repo** [bluedream1121/REKD#7]
In the paper, the detector is evaluated using the GIFT descriptor as well, but this code only allows for the other 3 descriptors to be used. Would it be possible to get the code for the GIFT implementation too? Since it gave some of the best results in the paper, it is odd that it has been left out.
Thanks.

**Comment by bluedream1121** [comment]
Our keypoint detector consistently outperforms the baseline keyNet when combined with the hardnet, sosnet, and hynet descriptors. (Table 1 in paper) The results for the GIFT descriptor were experimented with for possible additional performance improvements and are not intended as a comparison when experimenting with the keypoint detector. 
In other words, the GIFT descriptor experiments are meant to show integration with other dense descriptors, not as a primary result.

Therefore, we do not provide experiments with GIFT descriptors, as they are not relevant for comparison to verify the effectiveness of this paper.

It should be easy to implement using the following GIFT repository. We used the pre-trained model provided by the authors to obtain our scores. 
https://github.com/zju3dv/GIFT
