### ISSUE TITLE
Testing on own images

### ISSUE THREAD

**Issue by eddienewton** [bluedream1121/REKD#9]
Hi,

Great results!  Is there code to test on own images?  Or should I work off of the demo code?

I noticed that this has cv2 and scilearn functions for the feature extraction.  I see that KeyNet released a pytorch version.  Is the inference time a lot slower than KeyNet?  And is it worth it to create a pytorch version of this?  

Thanks

**Comment by bluedream1121** [comment]
Hello. 

The inference time of REKD is slower than Key.Net because the intermediate features of equivariant networks have more channel size at inference time. 

The released code is already implemented by pytorch.
